apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opensampl.fullname" . }}-db-secret
  labels:
    {{- include "opensampl.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.db.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.password | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.db.grafanaPassword | quote }}
