{
 "title": "Geospatial and Timing Combined Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "clock_name",
    "query": "SELECT uuid AS __value, COALESCE(name, CONCAT(ip_address, ' Interface ', probe_id)) AS __text FROM castdb.probe_metadata WHERE vendor in ('ADVA', 'MicrochipTP4100');"
   },
   {
    "name": "resolution",
    "query": "1min, 5min, 15min, 1hour, 6hour, 1day"
   }
  ]
 },
 "panels": [
  {
   "title": "Probe Location Map",
   "type": "geomap",
   "description": "Dot size corresponds to the number of selected probes at the location. \nColor corresponds to whether there are any public probes at the site (there may be additional private probes or probes with different reading types) ",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n    pm.name as \"Clock\",\n    l.name as \"Location Name\",\n    l.latitude,\n    l.longitude,\n    l.campus\nfrom castdb.campus_locations l left join castdb.probe_metadata pm on l.uuid = pm.location_uuid\nwhere pm.uuid in (${clock_name:sqlstring});"
    },
    {
     "rawSql": "SELECT\n    l.latitude,\n    l.longitude,\n    l.campus,\n    sum(\n        CASE\n            when pm.public = True and pm.vendor in ('ADVA', 'MicrochipTP4100') then 1 else 0\n        end \n    ) as visible_clocks,\n    sum(\n        CASE\n            when pm.uuid in (${clock_name:sqlstring}) then 1 else 0\n    end \n    ) as selected_clocks\n    from castdb.campus_locations l left join castdb.probe_metadata pm on l.uuid = pm.location_uuid\n    where l.public = True\n    group by\n    l.latitude, l.longitude, l.campus;"
    }
   ]
  },
  {
   "title": "Public Active Probes ",
   "type": "stat",
   "description": "Number of public probes that we have any data for. ",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as \"Total Clock Probes\" FROM castdb.probe_metadata where uuid in ($clock_name)"
    }
   ]
  },
  {
   "title": "Raw Record Count in Selected Time Range",
   "type": "bargauge",
   "description": "Number of raw time entries per clock in the given time period, selected above",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  coalesce(pm.name, concat(pm.ip_address, 'Inteface', pm.probe_id)) as \"Clock Probe\", \n  COUNT(*) as \"Total Records\" \nFROM castdb.probe_data pd\njoin castdb.probe_metadata pm on pd.probe_uuid = pm.uuid \nwhere pm.uuid in (${clock_name:sqlstring})\nAND pd.\"time\" >= $__timeFrom()\nAND pd.\"time\" <= $__timeTo()\ngroup by pm.uuid, pm.name, pm.ip_address, pm.probe_id;"
    }
   ]
  },
  {
   "title": "Time Error - Clock Time vs GNSS",
   "type": "timeseries",
   "description": "Average time error \n(averaged on selected resolution)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC') AS time,\n  coalesce(pm.name, concat(pm.ip_address, ' Interface ', pm.probe_id)),\n  AVG(pd.value_float) * 1e9 AS value\nFROM castdb.probe_data pd join castdb.probe_metadata pm on pd.probe_uuid = pm.uuid\nWHERE\n  $__timeFilter(pd.time)\n  AND pd.probe_uuid IN (${clock_name:sqlstring})\nGROUP BY \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC'),\n  pd.probe_uuid,\n  pm.name,\n  pm.ip_address,\n  pm.probe_id\nORDER BY \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC')\n"
    }
   ]
  },
  {
   "title": "Maximum Time Interval Error VS GNSS",
   "type": "timeseries",
   "description": "Time interval based on selected resolution",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC') AS time,\n  COALESCE(name, CONCAT(ip_address, ' Interface ', probe_id)),\n  (MAX(pd.value_float) - MIN(pd.value_float)) * 1e9 AS value\nFROM castdb.probe_data pd join castdb.probe_metadata pm on pd.probe_uuid = pm.uuid\nWHERE\n  $__timeFilter(pd.time)\n  AND pd.probe_uuid in (${clock_name:sqlstring})\nGROUP BY \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC'),\n  pd.probe_uuid,\n  pm.name,\n  pm.ip_address,\n  pm.probe_id\nORDER BY \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC')\n"
    }
   ]
  },
  { "title": "$clock_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "clock_name" },
  {
   "title": "Time Error - Clock Time vs GNSS",
   "type": "timeseries",
   "description": "Average time error \n(averaged on selected resolution)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC') AS time,\n  AVG(pd.value_float) * 1e9 AS value\nFROM castdb.probe_data pd\nWHERE\n  $__timeFilter(pd.time)\n  AND pd.probe_uuid = ${clock_name:sqlstring}\nGROUP BY \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC'),\n  pd.probe_uuid\nORDER BY \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC')\n"
    }
   ]
  },
  {
   "title": "Maximum Time Interval Error",
   "type": "timeseries",
   "description": "Time interval based on selected resolution",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC') AS time,\n  (MAX(pd.value_float) - MIN(pd.value_float)) * 1e9 AS value\nFROM castdb.probe_data pd\nWHERE\n  $__timeFilter(pd.time)\n  AND pd.probe_uuid = ${clock_name:sqlstring}\nGROUP BY \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC'),\n  pd.probe_uuid\nORDER BY \n  time_bucket(${resolution:sqlstring}, pd.time AT TIME ZONE 'UTC')\n"
    }
   ]
  }
 ]
}