site_name: openSAMPL Documentation
nav:
- Home: index.md
- Getting Started:
  - getting-started/index.md
  - Installation: getting-started/installation.md
  - Quickstart: getting-started/quickstart.md
- Guides:
  - guides/index.md
  - Configuration: guides/configuration.md
  - CLI:
    - Basic Usage: guides/opensampl-cli.md
    - Expected Table Format: guides/expected_table_format.md
    - Create: guides/create_probe_type.md
  - Server: guides/opensampl-server.md
  - Collect: guides/collection.md
  - Automatic Ingest: guides/automatic_ingest.md
  - NTP Extension: guides/ntp-extension.md
  - Random Data: guides/random-data-generation.md
- API:
  - index: api/index.md
  - cli: api/cli.md
  - collect:
    - cli: api/collect/cli.md
    - microchip:
      - tp4100:
        - collect_4100: api/collect/microchip/tp4100/collect_4100.md
      - twst:
        - context: api/collect/microchip/twst/context.md
        - generate_twst_files: api/collect/microchip/twst/generate_twst_files.md
        - readings: api/collect/microchip/twst/readings.md
    - modem: api/collect/modem.md
  - config:
    - base: api/config/base.md
    - server: api/config/server.md
    - tp4100: api/config/tp4100.md
  - create:
    - create_vendor: api/create/create_vendor.md
    - insert_markers: api/create/insert_markers.md
  - db:
    - access_orm: api/db/access_orm.md
    - orm: api/db/orm.md
  - helpers:
    - geolocator: api/helpers/geolocator.md
  - load:
    - data: api/load/data.md
    - routing: api/load/routing.md
    - table_factory: api/load/table_factory.md
  - load_data: api/load_data.md
  - metrics: api/metrics.md
  - mixins:
    - collect: api/mixins/collect.md
    - random_data: api/mixins/random_data.md
  - references: api/references.md
  - server:
    - backend:
      - main: api/server/backend/main.md
    - cli: api/server/cli.md
    - cli2: api/server/cli2.md
  - vendors:
    - adva: api/vendors/adva.md
    - base_probe: api/vendors/base_probe.md
    - constants: api/vendors/constants.md
    - microchip:
      - tp4100: api/vendors/microchip/tp4100.md
      - twst: api/vendors/microchip/twst.md
    - ntp: api/vendors/ntp.md
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths:
        - .
markdown_extensions:
- mkdocs-click
theme:
  name: material
  features:
  - navigation.sections
  - navigation.tracking
  - navigation.path
  - navigation.tabs
  - navigation.indexes
