apiVersion: v1
kind: Service
metadata:
  name: {{ include "opensampl.name" . }}-db
  labels:
    {{- include "opensampl.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
      name: postgres
  selector:
    app: {{ include "opensampl.name" . }}-db
