apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "opensampl.fullname" . }}-migrations
  labels:
    {{- include "opensampl.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    metadata:
      labels:
        app: {{ include "opensampl.name" . }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrations
          image: {{ .Values.migrations.image }}
          env:
            - name: DATABASE_URL
              values: postgresql://{{ .Values.db.username }}:{{ .Values.db.password }}@{{ include "opensampl.name" . }}-db:{{ .Values.db.port }}/{{ .Values.db.database }}