apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opensampl.fullname" . }}-backend
  labels:
    {{- include "opensampl.labels" . | nindent 4 }}
    role: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "opensampl.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      role: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "opensampl.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        role: backend
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            - sh
            - -c
            - >
              until nc -z {{ include "opensampl.fullname" . }}-db {{ .Values.db.port }};
              do echo "Waiting for DB...";
              sleep 3;
              done;
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@{{ include "opensampl.fullname" . }}-db:{{ .Values.db.port }}/{{ .Values.db.database }}
            - name: POSTGRES_USER
              value: {{ .Values.db.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "opensampl.fullname" . }}-db-secret
                  key: POSTGRES_PASSWORD
            - name: BACKEND_LOG_LEVEL
              value: {{ .Values.backend.logLevel | default "INFO" | quote }}
            - name: USE_API_KEY
              value: {{ .Values.backend.useApiKey | default "false" | quote }}
            {{- with .Values.backend.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}