name: Helm Chart CI/CD

on:
  push:
    branches: [ helm-deploy ]
  pull_request:
    branches: [ helm-deploy ]
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
   
    strategy:
      matrix:
        service:
          - name: db
            context: ./opensampl/db
          - name: backend
            context: ./opensampl/backend
          - name: grafana
            context: ./opensampl/server/grafana
          #- name: migrations
           # context: ./opensampl/migrations
   
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push DB image
        uses: docker/build-push-action@v5
        with:
          context: ./opensampl/db
          push: true
          tags: ghcr.io/ornl/opensampl-db:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  helm:
    runs-on: ubuntu-latest
    needs: build-docker-images
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Helm Lint
        run: helm lint ./helm

      - name: Package Chart
        run: helm package ./helm

      - name: Push to GHCR
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          helm registry login ghcr.io -u $GITHUB_ACTOR -p $CR_PAT
          helm push opensampl-*.tgz oci://ghcr.io/ornl/charts