name: Lint with Ruff
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: check
      - uses: astral-sh/ruff-action@v3
        with:
          args: format --check
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.3"
      - name: Set up Python
        run: uv python install
      - name: Sync project, including dev dependencies
        run: uv sync
      - name: Build static content
        run: |
          uv run python ./scripts/gen_api_docs.py
          uv run mkdocs build --clean