name: ADVA
parser: AdvaProbe
metadata_orm: AdvaMetadata
metadata_table: adva_metadata
metadata_fields:
  - name: 'type'
  - name: start
    type: TIMESTAMP
  - name: frequency
    type: Integer
  - name: timemultiplier
    type: Integer
  - name: multiplier
    type: Integer
  - name: title
  - name: adva_probe
  - name: adva_reference
  - name: adva_reference_expected_ql
  - name: adva_source
  - name: adva_direction
  - name: adva_version
    type: Float
  - name: adva_status
  - name: adva_mtie_mask
  - name: adva_mask_margin
    type: Integer