name: ADVA
parser: AdvaProbe
metadata_orm: AdvaMetadata
metadata_table: adva_metadata
metadata_fields:
  type:
  start:
    type: TIMESTAMP
  frequency:
    type: Integer
  timemultiplier:
    type: Integer
  multiplier:
    type: Integer
  title:
  adva_probe:
  adva_reference:
  adva_reference_expected_ql:
  adva_source:
  adva_direction:
  adva_version:
    type: Float
  adva_status:
  adva_mtie_mask:
  adva_mask_margin:
    type: Integer