name: GNSS
parser_class: GnssProbe
parser_module: gnss
metadata_orm: GnssMetadata
metadata_table: gnss_metadata
metadata_fields:
  - name: device
  - name: driver
  - name: fix_mode
    type: Integer
  - name: satellites_visible
    type: Integer
  - name: satellites_used
    type: Integer
  - name: latitude
    type: Float
  - name: longitude
    type: Float
  - name: altitude
    type: Float
  - name: gpsd_host
  - name: gpsd_port
    type: Integer
